### ISSUE TITLE
GitHub GraphQL return error when response body is too large

### ISSUE THREAD

**Issue by conwnet** [conwnet/github1s#105]
now GraphQL API will fetch multi level trees and blobs in one request, the response body maybe too large to report an error in this case.

we will get an error  in visiting`torvalds/linux` in the current implementation.

![image](https://user-images.githubusercontent.com/17734694/107843072-df489d00-6e02-11eb-8ef3-a18ef56dcf8c.png)

**Comment by xcv58** [comment]
I think we can remove one level to see whether it mitigates the issue.

**Comment by xcv58** [comment]
It seems for the Linux repo, the maximum level we could support is 2 levels. And for some extreme case, i.e. a text file has more than 30MB, there is no way to solve it.

![image](https://user-images.githubusercontent.com/503123/107861277-cdaec780-6df9-11eb-84b6-489a03ca96ea.png)


```
fragment TreeEntryFields on TreeEntry {
  oid
  name
  path
  type
}

fragment BlobFields on Blob {
  oid
  byteSize
  text
  isBinary
}

fragment TreeField on Tree {
  id
  entries {
    ...TreeEntryFields
    object {
      ...BlobFields
      ... on Tree {
        entries {
          ...TreeEntryFields
          object {
            ...BlobFields
          }
        }
      }
    }
  }
}

query objectQuery($owner: String!, $repo: String!, $expression: String!) {
  repository(name: $repo, owner: $owner) {
    id
    object(expression: $expression) {
      ...TreeField
    }
  }
}
```

@conwnet how about we reduce the query to 2 levels and test it against some big repo?

**Comment by xcv58** [comment]
PR #110

**Comment by conwnet** [comment]
It seems that's the only way now, we can provide a setting option for users to choose the preloading levels in the feature~

**Comment by xcv58** [comment]
The issue is mitigated
