### ISSUE TITLE
Terminal Integration

### ISSUE THREAD

**Issue by Sanchitbajaj02** [conwnet/github1s#107]
First of all, thanks for making this amazing project. It is helpful and easy to use. 
The only thing that I found out missing is the terminal. Is it possible to add the terminal and features to update and commit directly from here?

**Comment by softmarshmallow** [comment]
Here, we support terminal via command `surf .`
https://github.com/bridgedxyz/github.surf
https://github.com/bridgedxyz/surf-cli

**Comment by conwnet** [comment]
> First of all, thanks for making this amazing project. It is helpful and easy to use.
> The only thing that I found out missing is the terminal. Is it possible to add the terminal and features to update and commit directly from here?

github1s is build for read for preview code quickly, It is a pure static web application, it don't support edit code now, you can use [GitHub CodeSpaces](https://github.com/features/codespaces) or [gitpod](https://www.gitpod.io/) for a full online web IDE experience
