### ISSUE TITLE
Please add ipynb files readable too (in the form of .py files) [Feature Request]

### ISSUE THREAD

**Issue by elvinaqa** [conwnet/github1s#108]
There are tons of pushed code in the ipynb files from either Jupyter Notebook or Google colab, which is not currently supported by github1s. I would highly recommend adding that feature to convert ipynb files to .py files and make it readable in the browser as well. 

Thanks. 
Great project!

**Comment by Siddhant-K-code** [comment]
we are currently trying to implement Jupyter Notebook viewer, and this issue is a duplicate of #77

**Comment by elvinaqa** [comment]
Sorry didnt see that. Cool!
