### ISSUE TITLE
`yarn watch` does on work

### ISSUE THREAD

**Issue by gragib** [conwnet/github1s#113]
I got `vscode` installed and running, so I am fairly certain the build chain is working fine.

With `github1s`, this works:
```bash
yarn
yarn build
yarn serve
```
This does not work ever:
```bash
yarn
yarn watch
yarn serve  # in a separate terminal
```
I do not see any obvious errors in the first terminal. I see some errors in Chrome dev tools about unexpected semicolons.

**Comment by xcv58** [comment]
The `yarn watch` command needs a while to build all the dependencies. Could you please try to wait for more than 5 mins and try http://localhost:5000?

**Comment by gragib** [comment]
I left it running for 2 hours. Took an afternoon nap while it was doing its business. 😁

**Comment by gragib** [comment]
Let's put this issue on ice while I try something. Just found [this document](https://github.com/conwnet/github1s/blob/master/docs/guide.md#watch-mode).

**Comment by gragib** [comment]
Can't make it work. I am on macOS Big Sur.

**Comment by conwnet** [comment]
maybe you can run the watch steps which described in [watch.sh](https://github.com/conwnet/github1s/blob/master/scripts/watch.sh) one by one manually and detect what went wrong
