### ISSUE TITLE
npm Package?

### ISSUE THREAD

**Issue by nsisodiya** [conwnet/github1s#119]
How we can include in existing projects? 
Any plan to publish at npm package?

**Comment by conwnet** [comment]
How do you want to use it as a npm package?

**Comment by nsisodiya** [comment]
We have a product and we want to show it as a code editor.

**Comment by nsisodiya** [comment]
right now, we are using monaco-editor

**Comment by xcv58** [comment]
> We have a product and we want to show it as a code editor.

You might want to check this repo https://github.com/Felx-B/vscode-web

**Comment by nsisodiya** [comment]
@xcv58 - checking, looks interesting.

**Comment by nsisodiya** [comment]
@xcv58 - https://www.npmjs.com/package/vscode-web I found the package. but the doc is missing, How to use this package?

**Comment by xcv58** [comment]
> @xcv58 - https://www.npmjs.com/package/vscode-web I found the package. but the doc is missing, How to use this package?

Please reach out to https://github.com/Felx-B/vscode-web for your questions.
