### ISSUE TITLE
Set branch protection rules

### ISSUE THREAD

**Issue by xcv58** [conwnet/github1s#121]
Since there are multiple contributors have access to the repo. I suggest we set `master` as a protected branch with the below rules:

- Require pull request reviews before merging
- Require status checks to pass before merging

And turn the Merge button to support only `Allow squash merging` to keep the commit history clean & organized since there are might be ton of unorganized commits in PR.

![image](https://user-images.githubusercontent.com/503123/107916643-786ad700-6f1b-11eb-8210-610bda3bed06.png)

https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule

**Comment by conwnet** [comment]
thanks! I have set it~
