### ISSUE TITLE
Support privately owned repositories

### ISSUE THREAD

**Issue by lionuncle** [conwnet/github1s#123]
I could not see the code of my private repo. If I own this, I should be able to view it!

**Comment by gragib** [comment]
Did you add an Oauth token?

**Comment by xenowits** [comment]
@gragib how do we add an OAuth token?

**Comment by gragib** [comment]
![Screenshot_20210215-101922_Chrome.png](https://user-images.githubusercontent.com/2800980/107964451-4c7d3f00-6f77-11eb-9133-9210c3431f88.png)

**Comment by lionuncle** [comment]
@gragib worked for me Thanks!

**Comment by s-ayush2903** [comment]
How can this be done for gitlab1s? I cannot see any option for the same.

**Comment by Siddhant-K-code** [comment]
When you Open Any Private Repository with `1s` url, It will show you a screen like this: 

![image](https://user-images.githubusercontent.com/55068936/194929285-1974c68c-1de8-4471-8175-cd8b65664e3a.png)


Then you can proceed with further steps of creating the token and accessing it :)

**Comment by s-ayush2903** [comment]
Hi, thanks for giving your time. All that I see on opening a private repository at gitlab is the image attached below, whereas the screen you showed did appear when I (for the very first time) used github1s to browse private repository.
Is there something wrong that I'm doing or probably misconfigured from my end?

![image](https://user-images.githubusercontent.com/56556919/195039222-4e233fef-0024-4986-82a7-57fd78f6c810.png)

**Comment by conwnet** [comment]
hi @s-ayush2903 , Currently, gitlab1s does not support private repositories, but we have plan to support it in next months

**Comment by g1i1U** [comment]
> hi @s-ayush2903 , Currently, gitlab1s does not support private repositories, but we have plan to support it in next months

have you added it?

**Comment by conwnet** [comment]
> have you added it?

yes, you can add your GitHub OAuth Token to your GitHub1s Settings page to access your private repository.

**Comment by g1i1U** [comment]
> > have you added it?
> 
> yes, you can add your GitHub OAuth Token to your GitHub1s Settings page to access your private repository.

I meant gitlab private repos support, have you added it?

**Comment by conwnet** [comment]
> I meant gitlab private repos support, have you added it?

oh, thanks for the reminder, this feature is in another branch, I will merge it in a few days

**Comment by g1i1U** [comment]
> > I meant gitlab private repos support, have you added it?
> 
> oh, thanks for the reminder, this feature is in another branch, I will merge it in a few days

Please, thank you. Itis needed cuz GitHub private repos are forbidden in some countries.

**Comment by conwnet** [comment]
Hi @g1i1U, just like the GitHub private repositories, you can now access the private repositories on [gitlab1s.com](https://gitlab1s.com).
