### ISSUE TITLE
Support multiple file search

### ISSUE THREAD

**Issue by Mark-Fenng** [conwnet/github1s#13]
It looks like the current file search range is limited to opened files and I hope it will be able to  search in the entire project.
![image](https://user-images.githubusercontent.com/27533910/107210154-b610c100-6a3e-11eb-9409-d239b0f6be43.png)

**Comment by conwnet** [comment]
This feature will be supported it in the near future, I need to think about how to do it...

**Comment by Rishabh-Rathod** [comment]
+1

**Comment by khg0712** [comment]
🚀🚀🚀

**Comment by rish07** [comment]
@conwnet is someone working on this issue? If not I'd like to contribute

**Comment by conwnet** [comment]
> @conwnet is someone working on this issue? If not I'd like to contribute

Thank you, it hasn't started yet, how do you want to do this?

**Comment by rish07** [comment]
I did go through the Search code's documentation as well and you're right there. How would you use GraphQL API for this?

**Comment by conwnet** [comment]
> I did go through the Search code's documentation as well and you're right there. How would you use GraphQL API for this?

Use the GraphQL API to get contents of all files...😂 It's just a guess, the performance is too low in this way.
I think we should use the the REST Search API to implement the first version too.

**Comment by rish07** [comment]
Yes I think so too. Is there a community for this repo like slack or discord or something where we can discuss?

**Comment by conwnet** [comment]
> Yes I think so too. Is there a community for this repo like slack or discord or something where we can discuss?

I create an community here https://gitter.im/conwnet/github1s

**Comment by Siddhant-K-code** [comment]
> I create an community here https://gitter.im/conwnet/github1s

@xcv58 Please Join This Community for discussion :)

**Comment by bpartridge** [comment]
Sourcegraph's public API (which can index any public repository on demand) might be a great solution here; it supports regexes and case sensitivity, provides line numbers and offsets, and even allows searching across repos if multi-repo projects were ever something we wanted to support!

[Link to a live search with capabilities highlighted](https://sourcegraph.com/api/console#%7B%22query%22%3A%22query%20(%24query%3A%20String!)%20%7B%5Cn%20%20search(query%3A%20%24query)%20%7B%5Cn%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20__typename%5Cn%20%20%20%20%20%20limitHit%5Cn%20%20%20%20%20%20resultCount%5Cn%20%20%20%20%20%20approximateResultCount%5Cn%20%20%20%20%20%20missing%20%7B%5Cn%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20cloning%20%7B%5Cn%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20timedout%20%7B%5Cn%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20indexUnavailable%5Cn%20%20%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20%20%20...%20on%20Repository%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20__typename%5Cn%20%20%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20...%20on%20FileMatch%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20__typename%5Cn%20%20%20%20%20%20%20%20%20%20resource%5Cn%20%20%20%20%20%20%20%20%20%20lineMatches%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20preview%5Cn%20%20%20%20%20%20%20%20%20%20%20%20lineNumber%5Cn%20%20%20%20%20%20%20%20%20%20%20%20offsetAndLengths%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20...%20on%20CommitSearchResult%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20__typename%5Cn%20%20%20%20%20%20%20%20%20%20commit%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20oid%5Cn%20%20%20%20%20%20%20%20%20%20%20%20message%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22query%5C%22%3A%20%5C%22repo%3A%5Egithub.com%2Fgorilla%2Fmux%24%20Router%5C%22%5Cn%7D%22%7D)

https://about.sourcegraph.com/

**Comment by xcv58** [comment]
> Sourcegraph's public API (which can index any public repository on demand) might be a great solution here; it supports regexes and case sensitivity, provides line numbers and offsets, and even allows searching across repos if multi-repo projects were ever something we wanted to support!
> 
> [Link to a live search with capabilities highlighted (press the Play button at top to run)](https://sourcegraph.com/api/console#%7B%22query%22%3A%22query%20(%24query%3A%20String!)%20%7B%5Cn%20%20search(query%3A%20%24query)%20%7B%5Cn%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20__typename%5Cn%20%20%20%20%20%20limitHit%5Cn%20%20%20%20%20%20resultCount%5Cn%20%20%20%20%20%20approximateResultCount%5Cn%20%20%20%20%20%20missing%20%7B%5Cn%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20cloning%20%7B%5Cn%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20timedout%20%7B%5Cn%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20indexUnavailable%5Cn%20%20%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20%20%20...%20on%20Repository%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20__typename%5Cn%20%20%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20...%20on%20FileMatch%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20__typename%5Cn%20%20%20%20%20%20%20%20%20%20resource%5Cn%20%20%20%20%20%20%20%20%20%20lineMatches%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20preview%5Cn%20%20%20%20%20%20%20%20%20%20%20%20lineNumber%5Cn%20%20%20%20%20%20%20%20%20%20%20%20offsetAndLengths%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20...%20on%20CommitSearchResult%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20__typename%5Cn%20%20%20%20%20%20%20%20%20%20commit%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20oid%5Cn%20%20%20%20%20%20%20%20%20%20%20%20message%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22query%5C%22%3A%20%5C%22repo%3A%5Egithub.com%2Fgorilla%2Fmux%24%20Router%5C%22%5Cn%7D%22%7D)
> 
> https://about.sourcegraph.com/

Does Sourcegraph's public API support all public repo?

**Comment by rish07** [comment]
> Sourcegraph's public API (which can index any public repository on demand) might be a great solution here; it supports regexes and case sensitivity, provides line numbers and offsets, and even allows searching across repos if multi-repo projects were ever something we wanted to support!
> 
> [Link to a live search with capabilities highlighted (press the Play button at top to run)](https://sourcegraph.com/api/console#%7B%22query%22%3A%22query%20(%24query%3A%20String!)%20%7B%5Cn%20%20search(query%3A%20%24query)%20%7B%5Cn%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20__typename%5Cn%20%20%20%20%20%20limitHit%5Cn%20%20%20%20%20%20resultCount%5Cn%20%20%20%20%20%20approximateResultCount%5Cn%20%20%20%20%20%20missing%20%7B%5Cn%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20cloning%20%7B%5Cn%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20timedout%20%7B%5Cn%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20indexUnavailable%5Cn%20%20%20%20%20%20results%20%7B%5Cn%20%20%20%20%20%20%20%20...%20on%20Repository%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20__typename%5Cn%20%20%20%20%20%20%20%20%20%20name%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20...%20on%20FileMatch%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20__typename%5Cn%20%20%20%20%20%20%20%20%20%20resource%5Cn%20%20%20%20%20%20%20%20%20%20lineMatches%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20preview%5Cn%20%20%20%20%20%20%20%20%20%20%20%20lineNumber%5Cn%20%20%20%20%20%20%20%20%20%20%20%20offsetAndLengths%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20...%20on%20CommitSearchResult%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20__typename%5Cn%20%20%20%20%20%20%20%20%20%20commit%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20oid%5Cn%20%20%20%20%20%20%20%20%20%20%20%20message%5Cn%20%20%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22variables%22%3A%22%7B%5Cn%20%20%5C%22query%5C%22%3A%20%5C%22repo%3A%5Egithub.com%2Fgorilla%2Fmux%24%20Router%5C%22%5Cn%7D%22%7D)
> 
> https://about.sourcegraph.com/

Wouldn't using this API require the generation of access token doing GitHub auth? [https://docs.sourcegraph.com/api/graphql#quickstart](https://docs.sourcegraph.com/api/graphql#quickstart)

**Comment by bpartridge** [comment]
> Wouldn't using this API require the generation of access token doing GitHub auth? [docs.sourcegraph.com/api/graphql#quickstart](https://docs.sourcegraph.com/api/graphql#quickstart)

I don't believe so. From what I can tell the Sourcegraph documentation is tailored for people running it on their on infrastructure against private repos. But their *public* instance, which works on public repositories, doesn't require any auth. The following command will work, for instance, without any cookies or auth headers:

```
curl 'https://sourcegraph.com/.api/graphql' --data-binary $'{"query":"query ($query: String\u0021) {\\n  search(query: $query) {\\n    results {\\n      __typename\\n      limitHit\\n      resultCount\\n      approximateResultCount\\n      missing {\\n        name\\n      }\\n      cloning {\\n        name\\n      }\\n      timedout {\\n        name\\n      }\\n      indexUnavailable\\n      results {\\n        ... on Repository {\\n          __typename\\n          name\\n        }\\n        ... on FileMatch {\\n          __typename\\n          resource\\n          lineMatches {\\n            preview\\n            lineNumber\\n            offsetAndLengths\\n          }\\n        }\\n        ... on CommitSearchResult {\\n          __typename\\n          commit {\\n            oid\\n            message\\n          }\\n        }\\n      }\\n    }\\n  }\\n}\\n","variables":{"query":"repo:^github.com/gorilla/mux$ Router"}}'   --compressed
```

That said, for obscure/uncommonly used public repositories with lots of files, there may be some time required to index. I can't imagine it would be any slower, though, than trying to load the content over a client connection and index locally - and I doubt we want to run github1s servers to host indices in the cloud ourselves! Sourcegraph IMO seems like a very realistic and pragmatic compromise.

**Comment by conwnet** [comment]
> > Wouldn't using this API require the generation of access token doing GitHub auth? [docs.sourcegraph.com/api/graphql#quickstart](https://docs.sourcegraph.com/api/graphql#quickstart)
> 
> I don't believe so. From what I can tell the Sourcegraph documentation is tailored for people running it on their on infrastructure against private repos. But their _public_ instance, which works on public repositories, doesn't require any auth. The following command will work, for instance, without any cookies or auth headers:
> 
> ```
> curl 'https://sourcegraph.com/.api/graphql' --data-binary $'{"query":"query ($query: String\u0021) {\\n  search(query: $query) {\\n    results {\\n      __typename\\n      limitHit\\n      resultCount\\n      approximateResultCount\\n      missing {\\n        name\\n      }\\n      cloning {\\n        name\\n      }\\n      timedout {\\n        name\\n      }\\n      indexUnavailable\\n      results {\\n        ... on Repository {\\n          __typename\\n          name\\n        }\\n        ... on FileMatch {\\n          __typename\\n          resource\\n          lineMatches {\\n            preview\\n            lineNumber\\n            offsetAndLengths\\n          }\\n        }\\n        ... on CommitSearchResult {\\n          __typename\\n          commit {\\n            oid\\n            message\\n          }\\n        }\\n      }\\n    }\\n  }\\n}\\n","variables":{"query":"repo:^github.com/gorilla/mux$ Router"}}'   --compressed
> ```
> 
> That said, for obscure/uncommonly used public repositories with lots of files, there may be some time required to index. I can't imagine it would be any slower, though, than trying to load the content over a client connection and index locally - and I doubt we want to run github1s servers to host indices in the cloud ourselves! Sourcegraph IMO seems like a very realistic and pragmatic compromise.

Thanks @bpartridge and @sourcegraph, I have tried it, the Sourcegraph API is really powerful!

https://docs.sourcegraph.com/code_search/reference/queries
