### ISSUE TITLE
Support Syntax highlighting for Julia

### ISSUE THREAD

**Issue by jtschneider** [conwnet/github1s#139]
Hello, think this project is awesome!
I would love to see Syntax highlighting for Julia integrated. One could integrate the Julia extension for VS code https://github.com/julia-vscode/julia-vscode
or integrate the syntax files from https://github.com/julia-vscode/julia-vscode/tree/master/syntaxes
e.g.
https://raw.githubusercontent.com/julia-vscode/julia-vscode/master/syntaxes/julia.json

Cheers

**Comment by Siddhant-K-code** [comment]
Thanks for pointing out this issue, I will fork [julia-vscode](https://github.com/julia-vscode/julia-vscode) for this project and integrate it with this project.
