### ISSUE TITLE
要是有 Cloudflare worker 版本就更爽了

### ISSUE THREAD

**Issue by soffchen** [conwnet/github1s#14]
可以自己部署，还不需要服务器，还有 CDN

**Comment by conwnet** [comment]
现在就直接部署到 gh-pages 上面了，考虑过用 CDN 就是 cloudflare 在国内速度感人...

**Comment by ourongxing** [comment]
> 现在就直接部署到 gh-pages 上面了，考虑过用 CDN 就是 cloudflare 在国内速度感人...

既然都来 Github 了，还需要考虑这个么
