### ISSUE TITLE
Git submodules support

### ISSUE THREAD

**Issue by towzeur** [conwnet/github1s#143]
Hello, amazing project !

As a example, I created a simple repo with github1s as a [submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) : [test-gitmodules](https://github.com/towzeur/test-gitmodules)
![image](https://user-images.githubusercontent.com/25162836/108196411-6191d380-7119-11eb-9079-41aa10b2e980.png)

github1s manages to show the dependency as a file
![image](https://user-images.githubusercontent.com/25162836/108195993-dadcf680-7118-11eb-922e-f66029d70cb1.png)
But this error occurs when accessing this file
```
Unable to open 'github1s': Unable to read file 'github1s:/github1s' 
(NoPermissions (FileSystemError): Current OAuth Token Is Invalid, Please Change Another One.).
```

I think it should redirect to the proper dependency's github1s page (in this case here [https://github1s.com/conwnet/github1s](url) )

**Comment by conwnet** [comment]
thanks, work in progress, git submodules will be supported in these days~

**Comment by Siddhant-K-code** [comment]
Task Completed, Issue Resolved. Closing this now!
