### ISSUE TITLE
Any plans for similar service for GitLab

### ISSUE THREAD

**Issue by Cthutu** [conwnet/github1s#145]
This is an amazing piece of work.  I mean... REALLY.   But I am wondering if there ever will be a https://gitlab1s.com website?

**Comment by conwnet** [comment]
yes, we should do this, but it may be after we supported the main features of GitHub (like git submodule, PR, gist...)

**Comment by Cthutu** [comment]
I will look forward to it!  Thanks for the update.

**Comment by raimohanska** [comment]
At least the gitlab1s.com domain is reserved, hopefully for you. Really amazing thing this one!

Would you appreciate a Pull Request for Gitlab support?

**Comment by conwnet** [comment]
> At least the gitlab1s.com domain is reserved, hopefully for you. Really amazing thing this one!
> 
> Would you appreciate a Pull Request for Gitlab support?

thanks! I registered the `gitlab1s.com`.
any PR is welcome, but we may change the api during the main github featrure supporting.

**Comment by zvizvi** [comment]
@conwnet Maybe NPM also?
Somthing similar to [https://npm-explorer.tk](https://npm-explorer.tk/?p=github1s@0.0.0/package.json)

**Comment by conwnet** [comment]
`gitlab1s.com` is online now! The usage is the same as `github1s.com` 🚀

**Comment by sahil-ag** [comment]
Do we support setting up PRIVATE_TOKEN for gitlab projects (similar to github private projects?)

**Comment by conwnet** [comment]
> Do we support setting up PRIVATE_TOKEN for gitlab projects (similar to github private projects?)

Yes, now we use Sourcegraph API for gitlab public projects, we will support for gitlab private project with official API in the feature.
