### ISSUE TITLE
readme.md 文件名小写的时候识别不了when filename of readme.md is lowercase would not be recognized.

### ISSUE THREAD

**Issue by huangsen365** [conwnet/github1s#146]
readme.md 文件名小写的时候识别不了when filename of readme.md is lowercase would not be recognized.

**Comment by conwnet** [comment]
@huangsen365 Could you please offer an example? It works for me...

**Comment by huangsen365** [comment]
You can create two test projects: If you have project 1 using README.md and project 2 using readme.md
then try to use github1s to explorer the codes online, firstly project 1 using README.md it works fine
then project 2 will prompt <\README.md cannot be found> because project 2 is using readme.md

**Comment by conwnet** [comment]
> You can create two test projects: If you have project 1 using README.md and project 2 using readme.md
> then try to use github1s to explorer the codes online, firstly project 1 using README.md it works fine
> then project 2 will prompt <\README.md cannot be found> because project 2 is using readme.md

thanks, i caught it

**Comment by conwnet** [comment]
fixed in #172
