### ISSUE TITLE
请求状态码返回404, Body里面数据是正常的

### ISSUE THREAD

**Issue by FreeLoopC** [conwnet/github1s#15]
请求状态码返回404, Body里面数据是正常的
https://github1s.com/facebook/react
https://github1s.com/facebook/vs/workbench/workbench.web.api.css
https://github1s.com/facebook/vs/workbench/workbench.web.api.nls.js
https://github1s.com/facebook/vs/code/browser/workbench/workbench.js

还有我的Chrome69打开网页一片空白
改用FireFox78可以正常显示

**Comment by conwnet** [comment]
https://github1s.com/facebook/react
这个链接返回 404 是正常的，因为现在是部署在 gh-pages 上面的（就在这个项目的 gh-pages 分支），它的一个特性就是，如果请求的静态文件找不到就会返回 404.html，利用这个特性就可以实现类似单页应用的部署，可以看这个文档：
https://docs.github.com/en/github/working-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site

后面的那几个链接应该是有问题的，因为 facebook/vs 这个项目并不存在，所以什么都获取不到，看起来你是想获取静态文件，但是 url 好像拼错了

**Comment by FreeLoopC** [comment]
后面几个链接是访问https://github1s.com/facebook/react时同时请求的

**Comment by FreeLoopC** [comment]
![image](https://user-images.githubusercontent.com/20551753/107311199-e0a75c00-6ac8-11eb-8ad1-6e3fd4579bd6.png)

**Comment by conwnet** [comment]
这样的话...那应该就是编译出来的东西有问题了...你可以升级一下 Chrome（69 还是太低了），低版本兼容性的问题我测一下看看怎么回事儿
