### ISSUE TITLE
文件里的 follow link 不能打开

### ISSUE THREAD

**Issue by zer0fire** [conwnet/github1s#154]
如题，在 https://github1s.com/microsoft/vscode/blob/HEAD/src/tsconfig.json 里
![image](https://user-images.githubusercontent.com/26370252/108582017-939a7400-736b-11eb-8d89-c8252d13d07c.png)
`Ctrl + Click ` 打开后报
![image](https://user-images.githubusercontent.com/26370252/108582048-bdec3180-736b-11eb-8808-01b6ff037590.png)

**Comment by conwnet** [comment]
fixed
