### ISSUE TITLE
Add custom extension support

### ISSUE THREAD

**Issue by FFRaycoder** [conwnet/github1s#162]
At present, I understand the extension system of `github1s` as: only supports extensions in the `./extensions` directory.
Can the following function be added: the developer publishes the plugin to `npm`, and includes `github1s-plugin` in `keywords` in `package.json`? When users search for plug-ins, they can call the api of `npm` to search for packages containing specified keywords.

**Comment by xcv58** [comment]
I believe it's doable and it will bring more flexibility.

As an example, https://github.com/Felx-B/vscode-web, can install vim after it loads in the browser:
https://vscode-web-test-playground.azurewebsites.net/


![image](https://user-images.githubusercontent.com/503123/108798062-ac5c8280-7541-11eb-9d82-60d6a14807b8.png)

**Comment by FFRaycoder** [comment]
Yes, just like `vue-cli`'s plugin system.

**Comment by FFRaycoder** [comment]
> I believe it's doable and it will bring more flexibility.
> 
> As an example, https://github.com/Felx-B/vscode-web, can install vim after it loads in the browser:
> https://vscode-web-test-playground.azurewebsites.net/
> 
> ![image](https://user-images.githubusercontent.com/503123/108798062-ac5c8280-7541-11eb-9d82-60d6a14807b8.png)

Yes, just like vue-cli's plugin system.

**Comment by conwnet** [comment]
supported in #183 , you can install custom extensions now! but only the extension which support for browser version can be installed.
