### ISSUE TITLE
Support switching branch from SOURCE CONTROL panel

### ISSUE THREAD

**Issue by Hipska** [conwnet/github1s#168]
Currently, when you go to the SOURCE CONTROL panel, you see the following message:

> No source control providers registered.

I would expect to be able to change the current branch from this place.

**Comment by conwnet** [comment]
yes, we will support PR/diff/commits/branches here~
now you can press Shift+Ctrl/Command+P and select `GitHub1S: Switch to Other Branch/Tag` to switch branch

**Comment by conwnet** [comment]
![image](https://user-images.githubusercontent.com/17734694/111612837-da6b7480-8818-11eb-80d2-b04ab2dec197.png)

You can switch branch/tag by clicking here now~😁

**Comment by Hipska** [comment]
Sorry, will have to reopen. It still seems not possible from the SOURCE CONTROL panel..

Great that it is possible from the status bar though 👍

**Comment by conwnet** [comment]
> Great that it is possible from the status bar though 👍

It is possible to insert it into the SOURCE CONTROL panel.
I am working for the source control ability.
And the pull request support is in the way. #228 #235

You are right, maybe we can move the branches/tags into source control panel for more abilities. Thanks! ❤️
