### ISSUE TITLE
Search only search on opened files but not on all files

### ISSUE THREAD

**Issue by aprilmintacpineda** [conwnet/github1s#169]
Try it out here: https://github1s.com/aprilmintacpineda/react-fluxible

Steps to reproduce:

1. Go to src/useFluxibleStore.js
2. Go to search tab on the left sidebar.
3. Search for `import React from 'react';`
4. Works and shows the result:

![image](https://user-images.githubusercontent.com/21032419/108798504-e58c0580-75c8-11eb-80b3-3ef3f1352ca5.png)

5. Close the file.
6. Search again.
7. Now it doesn't work.

![image](https://user-images.githubusercontent.com/21032419/108798530-f177c780-75c8-11eb-9c54-0522274f307d.png)

I have seen related issues 

https://github.com/microsoft/vscode/issues/43758

**Comment by conwnet** [comment]
related #13

**Comment by conwnet** [comment]
fixed in #211 , it uses the sourcegraph API now, most public repositories are supported
