### ISSUE TITLE
Can't expand folders containing a hash/pound sign/number sign/octothorpe

### ISSUE THREAD

**Issue by PathogenDavid** [conwnet/github1s#170]
**Steps to reproduce:**

1. Go to https://github1s.com/InfectedLibraries/Biohazrd
2. In the file explorer, try to expand `Biohazrd` and then `#Declarations`

**Expected behavior:**

The folder expands to show its contents:

![image](https://user-images.githubusercontent.com/278957/108803107-78905580-755f-11eb-89af-6a76179b0407.png)

**Actual behavior:**

The folder appears to contain the contents of its parent:

![image](https://user-images.githubusercontent.com/278957/108803091-6e6e5700-755f-11eb-873d-f1f727aab350.png)

---------------

Looking at the request log, it appears that the folder name is getting dropped. It sends a request to `https://api.github.com/repos/InfectedLibraries/Biohazrd/git/trees/HEAD:Biohazrd/` instead of `https://api.github.com/repos/InfectedLibraries/Biohazrd/git/trees/HEAD:Biohazrd/%23Declarations` as expected.

I suspect the fix would be to URL encode the path here:

https://github.com/conwnet/github1s/blob/c4886ef8540b4231672360c5d51554f16326c048/extensions/github1s/src/api.ts#L69-L74

Unfortunately the setup script isn't working on either Windows or WSL for me otherwise I'd try the fix myself.

Love the concept of this project, looking forward to trying it in my workflow!

**Comment by PathogenDavid** [comment]
Thanks for the fix, @conwnet!

**Comment by conwnet** [comment]
> Thanks for the fix, @conwnet!

My pleasure, thanks for providing the clue of this bug
