### ISSUE TITLE
反馈【feedback】

### ISSUE THREAD

**Issue by keshiim** [conwnet/github1s#177]
1、在线打开项目的速度太慢
2、不支持代码搜索
示例：https://github.surf/keshiim/ZMJGanttChart/

**Comment by Arriv9l** [comment]
老哥你应该去 [surfcodes/surf: 🏄‍♂️ Surf GitHub code with VS Code. (with CLI, chrome extensions, also works for Gitlab)](https://github.com/surfcodes/surf) 提这个 Issue 吧。
你可以试试把 `github.surf` 换成 `github1s.com`，在我这儿快挺多的。
代码搜索的话，已经有人提过了 #13, #30，具体进度在 [Roadmap](https://github.com/conwnet/github1s/projects/1) 可见。

**Comment by xcv58** [comment]
Thank you @Arriv9l for clarification.
