### ISSUE TITLE
No detection of README.md when it is in .github/ directory

### ISSUE THREAD

**Issue by neg4n** [conwnet/github1s#178]
### Description
The site does not detect README when it is in `.github/` directory on the repository.
### Additional screenshot
![image](https://user-images.githubusercontent.com/57688858/109008484-ac799100-76ad-11eb-88d4-d0741d73e90a.png)

**Comment by dionsaputra** [comment]
Is this issue still open? I tried with the same repo and it seems work fine

<img width="1440" alt="Screen Shot 2021-03-14 at 16 32 59" src="https://user-images.githubusercontent.com/27763150/111063753-0ddd9480-84e3-11eb-82b8-cdcdd017318f.png">

**Comment by Siddhant-K-code** [comment]
@neg4n It's Working fine Now. 

Thanks, @dionsaputra,  for letting us know. 

Closing This Issue.
