### ISSUE TITLE
执行yarn watch命令报错，试了好几遍

### ISSUE THREAD

**Issue by shaodong0123** [conwnet/github1s#184]
执行yarn watch命令报错，尝试了好几遍还是不行，如下图：

![1](https://user-images.githubusercontent.com/32950529/109130874-2e8cb700-778d-11eb-80ba-b19320eeac7a.png)

提示 cd scripts/watch && node watch-src.js
系统找不到指定的路径。
请问是为什么啊？路径是有的啊。

![2](https://user-images.githubusercontent.com/32950529/109131247-917e4e00-778d-11eb-90a2-eba83777be8c.jpg)
试了几遍，还是不行。

**Comment by Lonor** [comment]
It may be that the first line causing the problem:
```sh
#!/usr/bin/env bash
```

Suggestion: use WSL / macOS / other Linux-based OS.

**Comment by conwnet** [comment]
MIngGW 应该不行，尝试一下@Lonor 所说的 WSL 或者 Linux
