### ISSUE TITLE
Welcome bot

### ISSUE THREAD

**Issue by himanshu007-creator** [conwnet/github1s#195]
A welcome bot will be really awesome to motivate first-time contributors.
I would like to work on it.

**Comment by xcv58** [comment]
I like the idea.

**Comment by himanshu007-creator** [comment]
> > A welcome bot will be really awesome to motivate first-time contributors.
> > I would like to work on it.
> 
> good idea, thanks～

Should I send a PR😁?

**Comment by Siddhant-K-code** [comment]
> Should I send a PR😁?

Yes, Go Ahead!

**Comment by himanshu007-creator** [comment]
> > Should I send a PR😁?
> 
> Yes, Go Ahead!

done #203
