### ISSUE TITLE
Disable Telemetry by default [default-settings]

### ISSUE THREAD

**Issue by ddaza** [conwnet/github1s#196]
This setting is enabled by default and I don't think it should be. Thoughts?

<img width="931" alt="Screen Shot 2021-02-27 at 2 20 07 PM" src="https://user-images.githubusercontent.com/290254/109399266-70416d00-7907-11eb-9985-ee9512ed64ff.png">

**Comment by conwnet** [comment]
Yes, I think so, we will disabled it by default in next release
