### ISSUE TITLE
can not use 

### ISSUE THREAD

**Issue by lightingtime** [conwnet/github1s#201]
whatever open a GitHub project, it shows `Unable to open '~': Unable to resolve resource github1s:/`
I read the `How it works` and find there is `you could try to set a GitHub OAuth Token. ` 
I google GitHub token but don't get the answer.
So must I set an OAuth app？

**Comment by conwnet** [comment]
You can check here:
https://github.com/conwnet/github1s/blob/master/docs/guide.md#rate-limit
and
https://github.com/conwnet/github1s#enabling-private-repositories
