### ISSUE TITLE
Allow to edit files and then create a pull request

### ISSUE THREAD

**Issue by justanotheranonymoususer** [conwnet/github1s#21]
Or at least export a patch file or something. That would be really cool 😀
Awesome project!

**Comment by ThiefMaster** [comment]
I don't care so much about the PR, but being able to edit a file just to copy slightly-changed code to paste somewhere would be great.

**Comment by conwnet** [comment]
I agree with this, and It is really possible to change file content and create an commit online through [GitHub API Docs](https://docs.github.com/en/rest/reference/git#commits), I can work for it in nearly future.

@ThiefMaster as for simple edit and paste code, you can choose "File -> New File" in activity bar to create an empty file and edit it, may be we can offer an quick way (may be a button or a command) to do it.

**Comment by ThiefMaster** [comment]
I meant an existing file in the repo - for example, when you are discussing something in an issue and want to paste a snipped from the repo with a some minor modifications.

**Comment by ritchxu** [comment]
GitHub has its own Codespaces product coming for that and more https://github.com/features/codespaces

**Comment by notpushkin** [comment]
@ritchxu There is also gitpod.io and some other offerings that allow this. I believe github1s is the “light” way to quickly look at (and probably edit) the repo (zero startup time, but no features requiring server-side support, like terminal or external language servers).

**Comment by xcv58** [comment]
I think this feature is doable, but we have to finish #12 and make some refactors to support this.

**Comment by SirWindfield** [comment]
I wanted to chime in and give another point of view. I kind of disagree with the PR feature. The great thing about `github1s` is that it spins up way faster than codespaces (cold and hot). It's great for poking around in a code base or when trying to see how someone did something without having to clone it.

As soon as it comes to editing though, I personally think that spinning up a codespace is superior. It supports persistence once created, your dotfiles are automatically copied over and it is tighter integrated into GitHub.

I personally think that maybe an `edit in codespace` button would be great if the repository has a `devcontainer.json` configured. I am not that familiar with Codespace APIs but maybe it's even possible to automatically create a PR with some default `devcontainer.json` from within `github1s`, as some kind of bridging between the two.

Looking forward to hear other opinions and thoughts!

**Comment by justanotheranonymoususer** [comment]
SirWindfield I kind of agree, but if implementing a simple editing feature
is possible (no auto complete, no linters) without hurting loading time,
then I think it's a functionality worth adding. It can be used for quick
pull requests. For more serious work, as you said, there are better fitting
tools, and of course the option to clone locally.

**Comment by SirWindfield** [comment]
I think I just assumed that because it's VSCode under the hook it would be the fully fledged experience :) A really simple editing functionality would probably be beneficial indeed!

**Comment by xcv58** [comment]
I think simple editing + downloadable patch is good enough.

**Comment by FractalHQ** [comment]
I’ve been replacing my GitHub graphql api powered REPL with isomorphic git running in web workers.  Could that be good for this use case perhaps?

**Comment by xcv58** [comment]
> I’ve been replacing my GitHub graphql api powered REPL with isomorphic git running in web workers. Could that be good for this use case perhaps?

@FractalHQ Could you please share more context? Any repo/demo will be appreciated.

**Comment by Felx-B** [comment]
At some point, I tried to do something like this, which cloned an entire repository in IndexedDB using isomorphic git.
https://github.com/Felx-B/vscode-gitfs/blob/fbo/init/gitfs/src/extension.ts

But to use it in VSCode UI, you need to reimplements git features in VSCode through [SourceControl](https://code.visualstudio.com/api/references/vscode-api#SourceControl)

**Comment by justanotheranonymoususer** [comment]
It's not quite what I meant, Gitpod doesn't take 1s to load :(

**Comment by conwnet** [comment]
> It's not quite what I meant, Gitpod doesn't take 1s to load :(

I know, it is for someone who need full ide abilities now, we will make continuous improvement in this feature. ( quick edit in 1s)
