### ISSUE TITLE
Support specifying OAuth token in URL

### ISSUE THREAD

**Issue by VelocityRa** [conwnet/github1s#210]
It'd be nice to be able to share links with the token already in the URL.
Especially useful for private repos where you have no choice but to enter it, so you have to ask every person you want to share a repo with to copy & paste it.

That's not currently possible is it?

**Comment by VelocityRa** [comment]
Oh, looks like these tokens can't be per repo? Hm, nevermind then 😅.

**Comment by conwnet** [comment]
This is technically possible, but the OAuth Token is very sensitive information, this may reduce people's sensitivity to token, I'm worried that someone might accidentally share their token. Token leakage can cause serious security problems
Should we support it?

**Comment by xcv58** [comment]
I think we should *NOT* support this. Especially URL is easily hackable even you have HTTP support. Because the URL itself could be easily accessed by others.
