### ISSUE TITLE
repositree a browser extension that helps to explore github repository now support github1s(vscode) mode

### ISSUE THREAD

**Issue by chouglesaud** [conwnet/github1s#232]
checkout the [extension](https://chrome.google.com/webstore/detail/repositree/lafjldoccjnjlcmdhmniholdpjkbgajo)

**Comment by xcv58** [comment]
Thanks @chouglesaud,

Please feel free to create a PR to include your extension in the list.

Thanks

**Comment by chouglesaud** [comment]
done :+1:

**Comment by xcv58** [comment]
Thank you!
