### ISSUE TITLE
Browse commits and allow to show commit code or show diff

### ISSUE THREAD

**Issue by justanotheranonymoususer** [conwnet/github1s#236]
The new pull requests feature is great. It will be awesome to enable something similar for commits:
* Show history of commits [like this](https://github.com/conwnet/github1s/commits/master)
* Show code of commit [like this](https://github.com/conwnet/github1s/tree/567a29d5c0b2e5b27833c12e52a0142619fa2dbc)
* Show commit diff [like this](https://github.com/conwnet/github1s/commit/567a29d5c0b2e5b27833c12e52a0142619fa2dbc)

**Comment by conwnet** [comment]
Thank you for your suggestion, It is worked in progress~❤️

**Comment by conwnet** [comment]
The commit feature works now~🚀

**Comment by justanotheranonymoususer** [comment]
You're a hero!
