### ISSUE TITLE
DevX Conf presentation

### ISSUE THREAD

**Issue by xcv58** [conwnet/github1s#248]
Hi @conwnet @Siddhant-K-code,

We will have a presentation about GitHub1s at the DevX Conf: https://www.notion.so/DevX-Conf-Manifesto-40fa33a4bb1e4346927ce2a7cdeba487

And I will prepare slides and record a 20 minutes video before April 10. 

The exact presentation time is Thu Apr 29, 2021, 09:00 - 09:30 (PDT). And we will join the Discord to chat with the conference attendee.

Could you please tell me (via [Twitter DM](https://twitter.com/xcv58) or email) your email address if you are interested to collaborate on the presentation material or just want to join the DevX Conf?

Thanks,
xcv58

**Comment by conwnet** [comment]
@xcv58 It sounds excited! Thanks for you work about this!❤️ I'd love to join the DevX Conf and watch your speech~🎉

**Comment by Siddhant-K-code** [comment]
Sounds Great. Your Twitter DMs are closed, you can get my email through my [GitHub profile](https://github.com/Siddhant-K-code) , (You Can Follow Also :) )

**Comment by Siddhant-K-code** [comment]
When will we get the Discord Invite Link for conf. ?

**Comment by Siddhant-K-code** [comment]
I think we should create an organization for this so that we can work on it full-fledged! and create the status page and more.
