### ISSUE TITLE
Option to show history of a single file

### ISSUE THREAD

**Issue by justanotheranonymoususer** [conwnet/github1s#261]
Perhaps by right clicking on a file in a file tree and choosing "Show history" from the menu

**Comment by conwnet** [comment]
Thank you for you advice❤️, it is already in the plan:
https://github.com/conwnet/github1s/wiki/Roadmap

**Comment by conwnet** [comment]
It works now~🚀 #268

**Comment by justanotheranonymoususer** [comment]
Awesome!

**Comment by justanotheranonymoususer** [comment]
@conwnet is it possible to show the date of each change in the history of changes? I'm not sure where it's best to show it, but I think that it's missing and will be nice to have.
