### ISSUE TITLE
support open gogs file system

### ISSUE THREAD

**Issue by jianboy** [conwnet/github1s#277]
**gogs** is a simple git project manager system developed with golang.   https://try.gogs.io/

it similar to github. and it's api is below: https://github.com/gogs/docs-api

the api is similar to github's api. So I suggest we can new a branch and add  implement the gogs api.

**Comment by jianboy** [comment]
this is my idea.
add a **extensions/gogs** folders， We can refer to extensions/github1s/github1sfs.ts to write a similar **gogs1sfs.ts**.

![image](https://user-images.githubusercontent.com/11532015/113828075-94218980-97b6-11eb-8c04-c73ad0cb477d.png)

**Comment by jianboy** [comment]
If we achieve it, then github1s can embed any gogs system.

**Comment by xcv58** [comment]
Related to #35
