### ISSUE TITLE
什么时候支持代码代码跳转等功能？

### ISSUE THREAD

**Issue by danielesk** [conwnet/github1s#278]
什么时候支持代码代码跳转等功能？

**Comment by conwnet** [comment]
这个功能已经在计划中了，您可以关注我们的最新 [Roadmap](https://github.com/conwnet/github1s/wiki/Roadmap) 来获取最新信息，我们正在想更好的支持这个特性，目前的的方案有 [Sourcegraph](https://sourcegraph.com) 和 [CodeWing](https://github.com/codewing-dev/codewing/)，如果您有更好的方案，欢迎您的建议，谢谢！

**Comment by danielesk** [comment]
@conwnet OK

**Comment by jianboy** [comment]
目前已经支持代码跳转了， 我这边java项目可以正确跳转。   

![image](https://user-images.githubusercontent.com/11532015/129574934-58344101-564a-4ef2-8767-a9b01ca789a6.png)

**Comment by danielesk** [comment]
@jianboy OK
