### ISSUE TITLE
Doc: add star charts over time

### ISSUE THREAD

**Issue by ttimasdf** [conwnet/github1s#286]
Just came across a funny project, which could display the stargazer changes over time. Maybe we could add that to the README 😃 it looks really impressive

https://starchart.cc/conwnet/github1s

[![Stargazers over time](https://starchart.cc/conwnet/github1s.svg)](https://starchart.cc/conwnet/github1s)

**Comment by xcv58** [comment]
That's a great idea, created https://github.com/conwnet/github1s/pull/287

**Comment by Siddhant-K-code** [comment]
added via #287
