### ISSUE TITLE
"Open File on GitHub" command?

### ISSUE THREAD

**Issue by borekb** [conwnet/github1s#288]
Would be great if there was an **Open File on GitHub** command that would open a new tab with the GitHub version of the current file.

If I didn't miss a way to do it more simply, this is what I can currently do: copy the URL, open new tab, paste URL, remove "1s". from the domain name. Would be great if this was a command.

_(Sorry if I missed an existing feature request – I'd think that I'm not the first one wanting this but my search skills are failing me.)_

**Comment by conwnet** [comment]
Thanks you for your suggestion! You can click here simply to open corresponding file on GitHub~🚀

![image](https://user-images.githubusercontent.com/17734694/115844833-d56e9600-a452-11eb-9457-b880a7c1c1c3.png)

**Comment by borekb** [comment]
Thanks, I missed that 🤦‍♂️. Possibly add this to the command palette so that it's findable via text search as well?

**Comment by conwnet** [comment]
> Thanks, I missed that 🤦‍♂️. Possibly add this to the command palette so that it's findable via text search as well?

I think so, we will add such a command to do this, thank you~

**Comment by pzhlkj6612** [comment]
Hello @conwnet . I found that the tooltip of the GitHub icon in the upper left corner is "Home". I think it would be better if the tooltip's content matches the actual function (i.e., open the current file on GitHub).

**Comment by conwnet** [comment]
> Hello @conwnet . I found that the tooltip of the GitHub icon in the upper left corner is "Home". I think it would be better if the tooltip's content matches the actual function (i.e., open the current file on GitHub).

I agree with you, we will change the tooltip in next version
