### ISSUE TITLE
Browser extension that adds an Open in VSCode UI element for single-click opens.

### ISSUE THREAD

**Issue by sergiotapia-papa** [conwnet/github1s#29]
![image](https://user-images.githubusercontent.com/52164116/107460870-ea5fac80-6b26-11eb-868b-6f742ee40f1c.png)

This would make it very easy to open and browse around code repositories without having to clone locally. I don't know how hard it would be to make + publish this so feel free to say it's out of scope.

This project is really nice, thanks for making it!

**Comment by febaoshan** [comment]
I try to do a nearly way, https://github.com/febaoshan/edge-extensions-github-code-viewer

**Comment by xcv58** [comment]
Hi @febaoshan 

I had a bunch of chrome extensions published in the Chrome store and might help. Could you please share more context about this? 

> I cannot publish it on chrome, welcome someone to publish it and tell me your effort.

**Comment by xcv58** [comment]
@sergiotapia-papa for your ref https://github.com/conwnet/github1s/issues/32#issuecomment-776464395

**Comment by xcv58** [comment]
There are extension links in https://github.com/conwnet/github1s#chrome-extensions

**Comment by febaoshan** [comment]
> Hi @febaoshan
> 
> I had a bunch of chrome extensions published in the Chrome store and might help. Could you please share more context about this?
> 
> > I cannot publish it on chrome, welcome someone to publish it and tell me your effort.
> 
> A CI publish setup for reference: https://github.com/xcv58/Tab-Manager-v2/blob/master/package.json#L19

Thanks.
