### ISSUE TITLE
This problem happened recently, and no code repository can be opened

### ISSUE THREAD

**Issue by ytianzaishui** [conwnet/github1s#299]
This problem happened recently, and no code repository can be opened

![image](https://user-images.githubusercontent.com/18025841/117572302-e54dd180-b104-11eb-965e-304e66e0274c.png)

**Comment by conwnet** [comment]
Please try to clear the browser cache and try again, it seems cause by the wrong cache policy.

I will continue to pay attention to this issue, thanks

**Comment by conwnet** [comment]
I got it.

According to the config in vercel.json, we cached the static files with `max-age=X` header, but we may get 404 esponse durning deploying, the default behavior for vercel would add the cache header to this 404 response, which caused the user can not get right resources anymore.

We will fix it in next release.
