### ISSUE TITLE
Multi cursor mode with ctrl+shift

### ISSUE THREAD

**Issue by HKalbasi** [conwnet/github1s#305]
Multi cursor mode with Alt and mouse click works but with ctrl+shift and up/down arrow keys doesn't work.

**Comment by conwnet** [comment]
Could you please more information for this issue? Thanks!

**Comment by HKalbasi** [comment]
In VSCode, when you hold shift and ctrl and press arrow keys up (or down), a new cursor will be added in previous (or next) line, but nothing happen in github1s.

**Comment by conwnet** [comment]
Got it! It seems this feature doesn't work in a read-only editors. It should cause by vscode, I will keep follow up it. Thanks~❤️

**Comment by HKalbasi** [comment]
Ah, the strange part is when you hold alt and click and it adds new cursors. I thought browser has problem with ctrl + shift shortcuts. So I will report it in upstream. Thank you!

**Comment by HKalbasi** [comment]
https://github.com/microsoft/vscode/issues/124373
