### ISSUE TITLE
Safari extension for github1s

### ISSUE THREAD

**Issue by code4you2021** [conwnet/github1s#310]
https://github.com/code4you2021/GitHub1s-For-Safari-Extension

![1](https://user-images.githubusercontent.com/83153991/119427941-9c219280-bd3e-11eb-985a-f4bba56eb702.png)
![2](https://user-images.githubusercontent.com/83153991/119427949-a0e64680-bd3e-11eb-870c-8bc534e8c443.png)

**Comment by conwnet** [comment]
Thank you so much for your great work! 🙏🎉 Could you please send a PR to add this the extension in [README.md](https://github.com/conwnet/github1s#third-party-related-projects)?

**Comment by code4you2021** [comment]
I have submitted a PR.
