### ISSUE TITLE
edge和chrome插件来了

### ISSUE THREAD

**Issue by febaoshan** [conwnet/github1s#32]
感谢大佬，借着你的这个东西，撸了个可以用于edge和chrome的插件。
源码和使用方法在这：https://github.com/febaoshan/edge-extensions-github-code-viewer

edge商店审核中，chrome无法支付5美元，所以现阶段只能下载源码解压后用浏览器的开发者模式加载解压的扩展程序。
有chrome开发者账号的可以直接发布插件，但是名字需要为：github-code-viewer。

谢谢。

**Comment by xcv58** [comment]
![image](https://user-images.githubusercontent.com/503123/107471161-8be3ff80-6b21-11eb-915c-11b2d7e41a70.png)

I submitted a chrome version and it should be ready in several hours.

I'm more than happy to transfer the ownership if @febaoshan or @conwnet want it.

**Comment by conwnet** [comment]
Thanks to everyone, any work for improving online code reading experience is welcome~

**Comment by xcv58** [comment]
It’s live now https://chrome.google.com/webstore/detail/github-code-viewer/ecddapgifccgblebfibdgkagfbdagjfn?hl=en&authuser=0

**Comment by xcv58** [comment]
The related links are in https://github.com/conwnet/github1s#third-party-related-projects

**Comment by febaoshan** [comment]
> It’s live now https://chrome.google.com/webstore/detail/github-code-viewer/ecddapgifccgblebfibdgkagfbdagjfn?hl=en&authuser=0

Thanks, it's live now on Edge too. https://microsoftedge.microsoft.com/addons/detail/githubcodeviewer/jaaaapanahkknbgdbglnlchbjfhhjlpi
