### ISSUE TITLE
Not working in opera browser

### ISSUE THREAD

**Issue by Ashwin-Raj18** [conwnet/github1s#324]
![image](https://user-images.githubusercontent.com/63547678/121392830-5df6b680-c96d-11eb-8bfb-9deda4847ea1.png)

**Comment by Ashwin-Raj18** [comment]
The editor loads but files on left panel does not open.

**Comment by Ashwin-Raj18** [comment]
The editor loads, but files des not load.

**Comment by conwnet** [comment]
Thanks you for reporting! I got it, we will fix it in next release~❤️
