### ISSUE TITLE
Not working in Opera GX browser

### ISSUE THREAD

**Issue by dngda** [conwnet/github1s#330]
![image](https://user-images.githubusercontent.com/35982346/122661018-5a0a3600-d1b0-11eb-9825-450d78fe660c.png)

**Comment by conwnet** [comment]
Thank you for your feedback, this bug is fixed in #325, it has workd in `https://beta.github1s.com` now, and it will take effect in `https://github1s.com` after the next release.❤️

**Comment by dngda** [comment]
Thanks.
Much appreciated.
