### ISSUE TITLE
Question: How to feed types to typescript language service

### ISSUE THREAD

**Issue by mecirmartin** [conwnet/github1s#332]
Hey, i'm playing with github1s version of vscode and i woould like to extend this and to be able to edit source code with rich intellisense. Right now, i'm getting intellisense for in scope objects. Is there a way to feed types of external packages (from node_modules) to language service so i would also get intellisense on these?

**Comment by conwnet** [comment]
Hi, did you want to run the it on browser? If the answer is yes, there are two choices:

1. Use [VSCode Remote](https://code.visualstudio.com/docs/remote/remote-overview), run the language server (and other native extensions) out of the browser.
2. Run all of the VSCode on browser, the extensions of browser version runs inside a webworker and there are some limits on it, many native extension can't worked fine. There are some solutions (Such as [stackblitz/webcontainer-core](https://github.com/stackblitz/webcontainer-core)) can help with this problem. I am planning to work on it.

**Comment by mecirmartin** [comment]
Yes, i plan on running it in browser. I assume that here is right place to start researching https://github.com/conwnet/github1s/blob/master/vscode-web-github1s/extensions/typescript-language-features/src/typescriptServiceClient.ts 
(It's in main part of vscode/extensions/typescript-language-features)

So I won't be able to extend this type of functionality through VSCode extension api, but i have to somehow feed the types in the main part of vscode, right?

**Comment by conwnet** [comment]
You can implement a Language Server by yourself use [Extension API](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide), but if you run full vscode extension servcices in browser, you will be restricted to only able to use webworker API now...

**Comment by mecirmartin** [comment]
I'm looking into this and i'm trying to register ts-language features, problem is that their are part of `vscode-web-github1s/lib/vscode/extensions`. I don't know how to import functions from this part of codebase, is it even allowed?
Particularly one function called `activate` takes only `vscode.ExtensionContext` and seemingly registers typescript language features, this function is located at `vscode-web-github1s/lib/vscode/extensions/typescript-language-features/src/extension.ts`
Is there any way to register this? I did try to put logs inside this function, but changes i make inside `/lib/vscode/` part of codebase don't take any effect. Am i doing something wrong?

Thanks

**Comment by conwnet** [comment]
> Is there any way to register this? I did try to put logs inside this function, but changes i make inside `/lib/vscode/` part of codebase don't take any effect. Am i doing something wrong?

If you want to modify vscode source, you should run `yarn watch-with-vscode` to start developing instead of `yarn watch`, it should be slower(because we full compile the source of vscode) than using the prebuilt vscode. Also the command isn't stable and if the command failed and throw an exception, please try more. 🙏
