### ISSUE TITLE
How can I switch to light theme?

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [conwnet/github1s#335]
Is it possible to change the theme from dark to light?

**Comment by xcv58** [comment]
Yes, you can do it by yourself:

![image](https://user-images.githubusercontent.com/503123/124641946-17995800-de44-11eb-9c71-a87b65f350e4.png)


![image](https://user-images.githubusercontent.com/503123/124641975-2253ed00-de44-11eb-9569-593fde414e8e.png)
![image](https://user-images.githubusercontent.com/503123/124642006-2d0e8200-de44-11eb-9f85-9fc7886e9e62.png)

**Comment by roychowdhuryrohit-dev** [comment]
Ok thanks.
