### ISSUE TITLE
[Question] github1s how to set a default config?

### ISSUE THREAD

**Issue by jianboy** [conwnet/github1s#337]
Can I ask a question here?

**How to set up a general configuration?**  for example, Hid the "Run and Debug" button. 

![image](https://user-images.githubusercontent.com/11532015/128614948-300264c9-31b8-4eba-8e00-1478c52175ab.png)

setting.json
```
{
    "workbench.editorAssociations": [
        {
            "viewType": "vscode.markdown.preview.editor",
            "filenamePattern": "*.md"
        }
    ]
}
```

**Comment by conwnet** [comment]
Sorry we don't support `Run add Debug` now😃

**Comment by jianboy** [comment]
> Sorry we don't support `Run add Debug` now😃

I mean how to hide this button. and any other global setting. Where is defalut **setting.json** in VSCode for web?

```
"extensions.autoCheckUpdates": false,
    "update.enableWindowsBackgroundUpdates": false,
    "update.showReleaseNotes": false,
    "update.mode": "default",
    "editor.tabCompletion": "on",
    "editor.formatOnPaste": true,
    "editor.formatOnSave": true,
    "editor.minimap.enabled": true,
    "editor.suggestSelection": "first",
    "editor.mouseWheelZoom": false, //缩放
    "editor.fontSize": 13,
    "editor.mouseWheelScrollSensitivity": 2,
    "editor.smoothScrolling": true,
    "editor.renderControlCharacters": true,
    "editor.formatOnType": true,
    "editor.fontFamily": "Monaco, 'Courier New', monospace",

```

**Comment by conwnet** [comment]
> I mean how to hide this button.

You can hide the `Run and Debug` Button follow below steps:

1. Right click the activity bar.
2. Turn off the `Run and Debug`

<img src="https://user-images.githubusercontent.com/17734694/128965613-c05be6fc-579f-4add-a061-02d21831d7f3.png" height="300px" />

> Where is defalut setting.json in VSCode for web?

You can change global settings here:

![image](https://user-images.githubusercontent.com/17734694/128978580-20ca3a2e-342e-4842-bbe9-23842866cdea.png)

**Comment by jianboy** [comment]
> > I mean how to hide this button.
> 
> You can hide the `Run and Debug` Button follow below steps:
> 
> 1. Right click the activity bar.
> 2. Turn off the `Run and Debug`


Thank you very much. I know how to set user config. But can Github1s hide the button by default? Besides, Can you add some other default settings? For example:

```
    "extensions.autoCheckUpdates": false,
    "update.enableWindowsBackgroundUpdates": false,
    "update.showReleaseNotes": false,
    "update.mode": "default",
    "editor.tabCompletion": "on",
    "editor.formatOnPaste": true,
    "editor.formatOnSave": true,
    "editor.minimap.enabled": true,
    "editor.suggestSelection": "first",
    "editor.mouseWheelZoom": false, //缩放
    "editor.fontSize": 13,
    "editor.mouseWheelScrollSensitivity": 2,
    "editor.smoothScrolling": true,
    "editor.renderControlCharacters": true,
    "editor.formatOnType": true,
    "editor.fontFamily": "Monaco, 'Courier New', monospace",

```

**Comment by conwnet** [comment]
> Besides, Can you add some other default settings?

I think we'd better to keep the default settings of vscode as much as possible. You can put your custom settings to `settings.json`:

<img src="https://user-images.githubusercontent.com/17734694/128982163-ca30aec2-e63b-4448-bd4d-baaf3c77717b.png" height="200px" />

Also, we may support to sync user settings cross devices in the future.

**Comment by jianboy** [comment]
Thank you very much!
