### ISSUE TITLE
Can not see anythings in firefox

### ISSUE THREAD

**Issue by jianboy** [conwnet/github1s#338]
![image](https://user-images.githubusercontent.com/11532015/128641434-051047b1-a921-4213-9c90-63e5a005c437.png)

**firefox version:** 70.0.1 (64 bit)

**error info:**

SyntaxError: expected expression, got '.'
github1s.com:141:43
SyntaxError: invalid identity escape in regular expression workbench.web.api.js:1:1
即使其 MIME 类型（“text/html”）不是有效的 JavaScript MIME 类型，仍已加载来自“https://github1s.com/vs/code/browser/workbench/workbench.js”的脚本。
github1s.com
SyntaxError: expected expression, got '<'
workbench.js:1

​

**Comment by conwnet** [comment]
It seems github1s can't get correct resources, could you please retry with a incognito window?

**Comment by Siddhant-K-code** [comment]
It seems working for me: 
![image](https://user-images.githubusercontent.com/55068936/128967437-80612c89-7ada-4dd3-97a1-6531e205b57a.png)

**Make Sure you are using an updated version of firefox.**

_My Browser & System config. :_ 

_**OS: Ubuntu 20.04.2.0 LTS
Browser: Firefox Version 90**_

**Comment by Siddhant-K-code** [comment]
Yeah, but In my Screenshot. `markdown.preview` seems to be not working on Firefox!

**Comment by jonasermert** [comment]
I have got the same problem.

**Comment by conwnet** [comment]
According to my test, github1s can't run on Firefox 70 now.
(If we want it to worked on Firefox 70, I have to change some code of VSCode)

Firefox 70 released on 2019, now the latest version of Firefox is 91. Why don't you upgrade it?

**Comment by jianboy** [comment]
I have not detected the firefox 91. I will download a new version firefox. thank you.
