### ISSUE TITLE
file list is not rendered if there is master branch.

### ISSUE THREAD

**Issue by JuHyung-Son** [conwnet/github1s#347]
If there is no master branch, it works.

**Comment by conwnet** [comment]
Could you please provide an url for this issue? it works for me during my test.

**Comment by JuHyung-Son** [comment]
it's https://github.com/UpstageAI/aiplatform-server but it is organization repo

**Comment by Siddhant-K-code** [comment]
It's a private repo.

you can follow [this](https://github.com/conwnet/github1s#enabling-private-repositories) for private repo.

**Comment by JuHyung-Son** [comment]
I already did it.
For some repositories without master branch is working, but some repos with master branch does not work.

**Comment by conwnet** [comment]
> For some repositories without master branch is working, but some repos with master branch does not work.

Does it work if you specify the branch name? for example:

https://github.com/UpstageAI/aiplatform-server/tree/master

**Comment by JuHyung-Son** [comment]
it still does not showing.

**Comment by conwnet** [comment]
> it still does not showing.

Is there any errors that displayed on Browser Devloper Tools Control?
(Please don't forget remove the sensitive data if you want to paste the errors here.)

**Comment by JuHyung-Son** [comment]
I followed this error. (create new token) and now it works. :)

```
  ERR Unable to read file 'github1s:/.vscode/tasks.json' (NoPermissions (FileSystemError): API Rate Limit Exceeded, Please Change Another OAuth Token.): Error: Unable to read file 'github1s:/.vscode/tasks.json' (NoPermissions (FileSystemError): API Rate Limit Exceeded, Please Change Another OAuth Token.)
    at o.doReadFileStream (https://github1s.com/static/f8b45d6/vscode/vs/workbench/workbench.web.api.js:626:46065)
    at async o.doReadFile (https://github1s.com/static/f8b45d6/vscode/vs/workbench/workbench.web.api.js:626:45171)
    at async Object.factory (https://github1s.com/static/f8b45d6/vscode/vs/workbench/workbench.web.api.js:626:45086)
```
