### ISSUE TITLE
Support for private repositories

### ISSUE THREAD

**Issue by stanleynguyen** [conwnet/github1s#36]
Probably we can do it through Github OAuth App with repo read permission

**Comment by conwnet** [comment]
I think it is already supported for private repositories if you have set you GitHub OAuth Token and set the correct permissions? It worked for me, I haved tried it just now.

**Comment by nereuseng** [comment]
Worked for me as well. Just wondering, when we set the token, where would the token store?

**Comment by conwnet** [comment]
I use the [VS Code ExtensionContext API](https://code.visualstudio.com/api/references/vscode-api#ExtensionContext), it stored in IndexedDB now. @nereuseng

**Comment by stanleynguyen** [comment]
Oh right I see that option. Thanks @conwnet

**Comment by myounus96** [comment]
> I think it is already supported for private repositories if you have set you GitHub OAuth Token and set the correct permissions? It worked for me, I haved tried it just now.

How we can set up that for github1s. I knew how we can generate a token from GitHub, but didn't get where we should paste that to grant github1s access. Thanks

**Comment by clementprevot** [comment]
@myounus96 I was wondering this like you for about an hour. And then, I randomly clicked on the "Update OAuth Token" tile on the right of the welcome screen. Doing this will trigger a prompt to enter the OAuth token.

You just have to click on the tile and avoid to click on the link that is inside of the tile 😅 

![image](https://user-images.githubusercontent.com/6450505/107657010-04af9c80-6c85-11eb-9ac8-0117c150d89f.png)

**Comment by myounus96** [comment]
> @myounus96 I was wondering this like you for about an hour. And then, I randomly clicked on the "Update OAuth Token" tile on the right of the welcome screen. Doing this will trigger a prompt to enter the OAuth token.
> 
> You just have to click on the tile and avoid to click on the link that is inside of the tile 
> 
> ![image](https://user-images.githubusercontent.com/6450505/107657010-04af9c80-6c85-11eb-9ac8-0117c150d89f.png)

Oh man 😄

**Comment by timbaileyjones** [comment]
> @myounus96 I was wondering this like you for about an hour. And then, I randomly clicked on the "Update OAuth Token" tile on the right of the welcome screen. Doing this will trigger a prompt to enter the OAuth token.
> 
> You just have to click on the tile and avoid to click on the link that is inside of the tile 😅
> 
> ![image](https://user-images.githubusercontent.com/6450505/107657010-04af9c80-6c85-11eb-9ac8-0117c150d89f.png)

I don't see the tile you're talking about.  Can you post a screenshot OF THE TILE, please?

**Comment by myounus96** [comment]
> > @myounus96 I was wondering this like you for about an hour. And then, I randomly clicked on the "Update OAuth Token" tile on the right of the welcome screen. Doing this will trigger a prompt to enter the OAuth token.
> > You just have to click on the tile and avoid to click on the link that is inside of the tile sweat_smile
> > ![image](https://user-images.githubusercontent.com/6450505/107657010-04af9c80-6c85-11eb-9ac8-0117c150d89f.png)
> 
> I don't see the tile you're talking about. Can you post a screenshot OF THE TILE, please?

Try opening a private repo then you will see this Tile.

**Comment by clementprevot** [comment]
> > @myounus96 I was wondering this like you for about an hour. And then, I randomly clicked on the "Update OAuth Token" tile on the right of the welcome screen. Doing this will trigger a prompt to enter the OAuth token.
> > You just have to click on the tile and avoid to click on the link that is inside of the tile 😅
> > ![image](https://user-images.githubusercontent.com/6450505/107657010-04af9c80-6c85-11eb-9ac8-0117c150d89f.png)
> 
> I don't see the tile you're talking about. Can you post a screenshot OF THE TILE, please?

The screenshot is literally in the comment you quoted 😅

**Comment by timbaileyjones** [comment]
It's still not anywhere on my screen. Let's try this: *What URL contains the "welcome screen"?*
Currently, I'm looking at the README.md for one of my clients' private repos, but with "github1s.com" as the hostname in the URL.

**Comment by conwnet** [comment]
> It's still not anywhere on my screen. Let's try this: _What URL contains the "welcome screen"?_
> Currently, I'm looking at the README.md for one of my clients' private repos, but with "github1s.com" as the hostname in the URL.

@timbaileyjones you can also set an OAuth Token here
![image](https://user-images.githubusercontent.com/17734694/108830523-7207e980-7604-11eb-8e0f-cc1e4c973423.png)
