### ISSUE TITLE
"Authenticating to GitHub" modal doesn't go away

### ISSUE THREAD

**Issue by akash-joshi** [conwnet/github1s#372]
Hey there! I'm a happy user of GitHub1s, but today I'm seeing the "Authenticating to GitHub" modal. This is fine, but closing it doesn't make it go away permanently. It comes back if I remove focus from the window and bring back focus again.

This is on Firefox 94.0.2 on Windows 11

**Comment by xcv58** [comment]
Thanks for your feedback @akash-joshi.

Could you please share a screenshot about this bug?

**Comment by ramanova** [comment]
![image](https://user-images.githubusercontent.com/5911161/145780630-727cbaf2-0389-47e7-9197-68ce281ecb8f.png)
Getting this modal on every new file open, ever 30 seconds. I don't feel comfortable granting permissions to my account for the tool (no matter how useful and great it is ).

**Comment by conwnet** [comment]
> Getting this modal on every new file open, ever 30 seconds. I don't feel comfortable granting permissions to my account for the tool (no matter how useful and great it is ).

@ramanova 

I am sorry for that. The Authenticating Modal only popup when you met [GitHub REST API RateLimiting](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting). And when some anonymous user got the rate limiting error, the GitHub API won't return any valid data in current time window (this is usually an hour).

> For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests.

We are considering using the other API for public repositories to avoid this, but it is still in progress.

**Comment by ramanova** [comment]
Understood, thank you!

**Comment by conwnet** [comment]
Now we use Sourcegraph api first for public repositories to avoid asking an token
