### ISSUE TITLE
Code cannot be collapsed

### ISSUE THREAD

**Issue by marsggbo** [conwnet/github1s#373]
For example, I cannot collapse this line in `https://github1s.com/researchmm/NEAS/blob/main/lib/models/NEAS_subnet.py#L22-L23`.

There is no button to collapse the code

![image](https://user-images.githubusercontent.com/13477956/144624607-b87ca9c1-fd9f-4032-b6a6-fe1b24861468.png)

**Comment by conwnet** [comment]
Thanks you for your feedback.❤️

Yes I see this problem and it seems to be cause by `anycode` extension. (I add it as a builtin extension in #364)

The temporary fast solution is disable this extension: Activity Bar -> Extensions -> Filter Extension with `@builtin` label -> anycode -> disable

we will fix this problem as soon.
