### ISSUE TITLE
Annoying authentication modal

### ISSUE THREAD

**Issue by canuysal** [conwnet/github1s#396]
Authentication modal forces users to sign in via github. If i dont, it asks every other second. Please only ask once or when required. It's annoying and feels like a scam.

**Comment by canuysal** [comment]
Oh, I get it. Does it access my private repos when i authenticate it? Maybe
it can help new users to put the purpose of authentication as info on the
modal.

**Comment by conwnet** [comment]
> Does it access my private repos when i authenticate it?

A: Only if when you visit a private repository with GitHub1s.

We don't save any user infomations. the auth token only saved in your local browser.

**Comment by conwnet** [comment]
Now we use Sourcegraph api first for public repositories to avoid asking an token
