### ISSUE TITLE
Fuzzy file search

### ISSUE THREAD

**Issue by easbar** [conwnet/github1s#40]
Ctrl+F already opens the 'Open File' pull-down. It also has autocomplete to navigate to the next directory. What would be really useful however is a fuzzy search to navigate to another file. This should be a lot easier to do than #13, because you 'only' need to search for the search string in the file names/tree.

**Comment by conwnet** [comment]
Work in progress~

**Comment by conwnet** [comment]
it should works now～

**Comment by conwnet** [comment]
fixed in #128
