### ISSUE TITLE
Blank page when Javascript is disabled

### ISSUE THREAD

**Issue by alexislefebvre** [conwnet/github1s#41]
I'm testing the [NoScript plugin](https://addons.mozilla.org/fr/firefox/addon/noscript/) and github1s display nothing when Javascript is disabled.

I suggest to add a text to explain that Javascript must be enabled to use that website. The [`<noscript>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript) tag could be used.

**Comment by lekandev** [comment]
Hi Please can I work on this? and would appreciate it if you could out me through where to  add that feature, I'm new with typescript

**Comment by Loryean** [comment]
Yes

**Comment by kanhegaonkarsaurabh** [comment]
I think #101 already fixed the issue.

**Comment by xcv58** [comment]
> I think #101 already fixed the issue @lekandev

Yes thanks for reminder

**Comment by alexislefebvre** [comment]
Thanks!
