### ISSUE TITLE
Bump vscode version

### ISSUE THREAD

**Issue by xcv58** [conwnet/github1s#420]
The https://github.com/microsoft/vscode-references-view was moved to https://github.com/microsoft/vscode/tree/main/extensions/references-view and the request to old version will return 404: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode/vsextensions/references-view/0.0.89/vspackage

Confirmed it also failed on master https://github.com/conwnet/github1s/runs/6928925119?check_suite_focus=true

**Comment by conwnet** [comment]
resolved in #421
