### ISSUE TITLE
File system provider for github1s:/ is not available.

### ISSUE THREAD

**Issue by rafaelsabino** [conwnet/github1s#427]
Good afternoon. I tried to run it several times to simulate in a local environment, but I can't load files to edit. The message that the file system is unavailable always appears.

![image](https://user-images.githubusercontent.com/12975702/176269190-b68d8894-d453-45a6-a78c-30ba72c91fc5.png)

Another point that after running, I can't get the files from http://localhost:5000/'username/repository'

If I'm in a public domain will it work?

What am I missing here?

**Comment by conwnet** [comment]
hi @rafaelsabino ，how did you startup this project? The easy way is just run `yarn && yarn watch`. and there is no domain limit. please clear the local browser cache and try again.

**Comment by rafaelsabino** [comment]
This is not the problem. It cannot resolve any repositories. Even starting in incognito tab and clearing cache. Another point that seems to be some kind of permission or plugin that cannot execute commands from the palette to open files from the pc or read repositories. It is running normally, but without access to repositories or files. And I did the commands `yarn && yarn watch` mentioned above, but without success.

![image](https://user-images.githubusercontent.com/12975702/176445187-de9dd403-9f24-4b59-b908-40cec4fa69c9.png)

**Comment by rafaelsabino** [comment]
I finally got it. I believe I have written cache of old modules and was rendering wrong. I deleted the entire project and reconfigured everything. It worked out. Thanks!
