### ISSUE TITLE
Add a route that can be searched directly with parameters

### ISSUE THREAD

**Issue by theowenyoung** [conwnet/github1s#428]
Hi, this is an amazing project, I want to use it as my blog's global search, is it a use case? 

Now I can manually enter <https://github1s.com/theowenyoung/blog>, and click the search button to search the files, but it's really helped if there is a direct route to navigate the search panel. something like:

`https://github1s.com/theowenyoung/blog/panel/search?q=term&files-include=content`

does it possible? or if can, I can try to submit a pr.

**Comment by Siddhant-K-code** [comment]
For Search, we use Sourcegraph GraphQL APIs. Which hits the endpoint: `https://sourcegraph.com/.api/graphql` with payload:

```json
{
  "variables": {
    "query": "repo:^github\\.com/theowenyoung/blog$ file:content -file:\\.git|\\.svn|\\.hg|CVS|\\.DS_Store|Thumbs.db|\\.crswap|node_modules|bower_components|\\.code-search \"term\" count:30"
  },
  "query": "query ($query: String!) {\n  search(query: $query) {\n    results {\n      __typename\n      limitHit\n      matchCount\n      approximateResultCount\n      missing {\n        name\n        __typename\n      }\n      cloning {\n        name\n        __typename\n      }\n      timedout {\n        name\n        __typename\n      }\n      indexUnavailable\n      results {\n        ... on FileMatch {\n          __typename\n          file {\n            name\n            path\n            __typename\n          }\n          lineMatches {\n            preview\n            lineNumber\n            offsetAndLengths\n            __typename\n          }\n        }\n        __typename\n      }\n    }\n    __typename\n  }\n}"
}
```


I am not 100% sure that is possible. But there should be some workaround for that.

WDYT? @conwnet @xcv58

**Comment by xcv58** [comment]
I think it's doable but we need to refactor the code to sync the search state with URL.

**Comment by conwnet** [comment]
yes, and I think this is reasonable, let me support it at next version
