### ISSUE TITLE
url is wrong

### ISSUE THREAD

**Issue by KyrieLii** [conwnet/github1s#437]
https://chrome.google.com/webstore/detail/open-in-vs-code-github1sc/neloiopjjeflfnecdlajhopdlojlkhll
https://chrome.google.com/webstore/detail/github1s/lodjfmkfbfkpdhnhkcdcoonghhghbkhe

i got 404 with above url , but i don't know the correct one , so anyone can fix this ? thanks ! 😁

**Comment by conwnet** [comment]
Thank you for your information, would you mind to open a PR to remove these outdated link?

**Comment by KyrieLii** [comment]
> Thank you for your information, would you mind to open a PR to remove these outdated link?

Of course 👉🏻 https://github.com/conwnet/github1s/pull/438
