### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by notpushkin** [conwnet/github1s#46]
Thank you for the project, it is really neat!

I assume it is quite different from things like https://github.com/cdr/code-server or gitpod.io, and that it works entirely in the browser – am I correct? If so, how is it done?

**Comment by pratik-chakravorty** [comment]
Would like to know more as well.

**Comment by Samuel-Martineau** [comment]
Also, who pays for the servers?

**Comment by sigaloid** [comment]
Replace "github" with "github1s" in a public repo URL to get access to a read only vscode viewer. Lots of people clone a repo just to look through it with vscode, so this makes it possible in browser. It does not have editing capabilities, it's just a read only viewer

**Comment by simook** [comment]
It is a static web application that is served via the Fastly CDN from a Varnish cache. Your browser is making direct API calls to Github for listing and viewing files.

**Comment by xcv58** [comment]
There is a dedicated doc to discuss how it works https://github.com/conwnet/github1s/blob/master/docs/guide.md

Thank you all for bringing up the question and answers!
