### ISSUE TITLE
Unable to get the latest files for GitHub projects

### ISSUE THREAD

**Issue by fhefh2015** [conwnet/github1s#463]
The project:
https://github.com/fhefh2015/Fast-GitHub

I opened the same project using Safari, without logging into Github.

![CleanShot 2022-11-15 at 17 14 53@2x](https://user-images.githubusercontent.com/14891797/201879670-956ce039-0b38-486e-bc71-209b442cbd34.png)

Open with github1s.com
https://github1s.com/fhefh2015/Fast-GitHub/tree/main/fast_github
PC Screenshot
<img width="1920" alt="CleanShot 2022-11-15 at 17 10 09@2x" src="https://user-images.githubusercontent.com/14891797/201878129-ce24ec39-edb6-4ec2-acc0-dd79a21c1df7.png">

Mobile Screenshot
<img width="413" alt="CleanShot 2022-11-15 at 17 17 35@2x" src="https://user-images.githubusercontent.com/14891797/201880090-9d17dc59-ef7f-4097-95a5-ee589f1644d6.png">

Open with github.dev
https://github.dev/fhefh2015/Fast-GitHub/tree/main/fast_github
<img width="1920" alt="CleanShot 2022-11-15 at 17 10 45@2x" src="https://user-images.githubusercontent.com/14891797/201878238-43162fc7-d154-4b2c-8651-4cfe8d46b66b.png">

**Comment by fhefh2015** [comment]
Thanks for the reply, the problem is solved.

**Comment by Siddhant-K-code** [comment]
> But I think there really may be a big latecy here, As I see, we should use GitHub API for logged users, and only use Sourcegraph Api for anonymous users default

Yes, @conwnet that would also be our issue of Code Search in Private Repositories. It doesn't work right now, we are calling Sourcegraph APIs by default (in both cases). I think we can directly consume GitHub APIs for GH logged in Users.
