### ISSUE TITLE
GitHub1s chrome extension

### ISSUE THREAD

**Issue by fhefh2015** [conwnet/github1s#47]
https://chrome.google.com/webstore/detail/github1s/lodjfmkfbfkpdhnhkcdcoonghhghbkhe/

![bQrnNlT](https://i.imgur.com/bQrnNlT.gif)

**Comment by filiptronicek** [comment]
Nice, came looking for this, could you also release the extension to Firefox? @fhefh2015

**Comment by xcv58** [comment]
Thank you @fhefh2015,

I added your link in README https://github.com/conwnet/github1s/commit/303747499dc1b558b613c3f344bb7e6610a57490
