### ISSUE TITLE
Github Auth Callback

### ISSUE THREAD

**Issue by nicklpeterson** [conwnet/github1s#477]
Hi, thanks for making this awesome project!
I'm working on setting it up for my organization on github enterprise server and ran into an issue with Oauth2 flow. When github redirects back, we end up with a url `localhost:5000?code=xxx` but it appears the post request to get the access token is never made. 
Could you explain what the correct callback url should be? Currently I'm working on it in localhost, with the plan to deploy at `git1s.myorg.com`.

**Comment by conwnet** [comment]
The whole auth process is referred to [GitHub Authorizing OAuth Apps Documentation](https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps).

The detailed steps for authenticating GitHub1s to GitHub:

1. User Click on 'Connect to GitHub' button in github1s auth page.
2. GitHub1s runs a custom command which is implemented [here](https://github.com/conwnet/github1s/blob/042eb4a4255d7d622c8f0b1e4ac066a0354e3dbe/resources/initialize.js#L163-L194). As you see, it will open the GitHub OAuth Page (`https://github.com/login/oauth/authorize?scope=repo,user:email&client_id=${client_id}`) in a new window (notice the `client_id` is provided by GitHub when you register an OAuth App), then open a `message listener` to wait the OAuth token that send back in Step 4.
3. Once User agrees to the OAuth request, GitHub will redirect to the **Authorization callback URL** which was filled in when you registered for the OAuth app, and provide a temporary `code` in url search parameters.
4. The implementation of the **Authorization callback URL** is [here](https://github.com/conwnet/github1s/blob/042eb4a4255d7d622c8f0b1e4ac066a0354e3dbe/api/github-auth-callback/index.js), it is a [Serverless Function](https://vercel.com/docs/concepts/functions/serverless-functions) that deployed in Vercel. it will use the code (received in Step 3), client_id (obtained when registering) and client_secret (obtained when registering) to exchange the `OAuth Token` with GitHub. Then use postMessage API to send the token back to GitHub1s (The message listener is registered in Step 2).
5. Finally, GitHub1s got the OAuth token and used it to read the data of repository.

If you deploy it yourself, you should register your own **GitHub OAuth App**, and the **Authorization callback URL** is set up by yourself.

Hope the above content is helpful to you.

**Comment by nicklpeterson** [comment]
Thank You! That is very helpful.
