### ISSUE TITLE
Ctrl+P doesn't prevent default print dialogue

### ISSUE THREAD

**Issue by RReverser** [conwnet/github1s#49]
Ctrl+P correctly brings up file autocomplete, but doesn't prevent the default browser action and so browser shows print dialog on top.

**Comment by felipefialho** [comment]
Yes, it's working in the first time but when we need to use `CMD+P` or `CTRL+P` again it opens the default print dialog.

**Comment by JammSpread** [comment]
This is related to #43.

**Comment by conwnet** [comment]
fixed in #165
