### ISSUE TITLE
Migrate the OSSInsight API to public endpoint

### ISSUE THREAD

**Issue by Mini256** [conwnet/github1s#522]
Earlier, OSSInsight officially released the [Public API](https://ossinsight.io/docs/api). Now we can migrate the API endpoint used in Github 1s to the new public endpoint.

Document:

https://ossinsight.io/docs/api/list-trending-repos

Example:

```shell
curl -L -X GET 'https://api.ossinsight.io/v1/trends/repos/?period=past_24_hours&language=All' \
-H 'Accept: application/json'
```

**Comment by Indrajeet911** [comment]
https://pin.it/1eyGtrb
