### ISSUE TITLE
Change "Open with Github1s" to simply "Github1s" (like Gitpod)

### ISSUE THREAD

**Issue by NateOsterfeld** [conwnet/github1s#56]
Takes up more space than necessary and is logically redundant.
To compare, Gitpod just has a button that says Gitpod and that's all it needs, it's the only button.

I suppose you could call it personal preference, but I think most people would prefer a change like this.

Thanks!

**Comment by xcv58** [comment]
The extension is owned by @fhefh2015 #47

@fhefh2015 could you please make the change?

**Comment by fhefh2015** [comment]
@NateOsterfeld 
@xcv58 
Great suggestion, I've updated the plugin and it's under review.
Now you can make some custom settings.

![image](https://user-images.githubusercontent.com/14891797/107600338-6e688000-6c5e-11eb-9f73-8c7c40394874.png)
