### ISSUE TITLE
Shortcut for closing terminal not Working

### ISSUE THREAD

**Issue by sagardxd** [conwnet/github1s#570]
When opening the repo using github1s
We can initially open the terimal using `` ctrl + ` `` .  But unable to close it again in the same way, we can do it in vscode locally.
This is a shortcut I use a lot.
If this is a feature to be added could guide me how to solve it.

**Comment by conwnet** [comment]
I am used to using `command + J` to toggle terminal panel views.

I guess it is because GitHub1s does not have a real terminal, so `terminal.active` command was not triggered correctly.

**Comment by sagardxd** [comment]
`` ctrl + J `` is working fine
