### ISSUE TITLE
天若有情天亦老, 人间正道是沧桑

### ISSUE THREAD

**Issue by snowman** [conwnet/github1s#60]
出自毛泽东写于 1949 年的七律诗《[人民解放军占领南京](https://baike.baidu.com/item/%E4%BA%BA%E6%B0%91%E8%A7%A3%E6%94%BE%E5%86%9B%E5%8D%A0%E9%A2%86%E5%8D%97%E4%BA%AC)》。

**Comment by csgka1** [comment]
这个项目果然出自国人之手，太暴力了
