### ISSUE TITLE
Not working on Microsoft Edge chromium browser

### ISSUE THREAD

**Issue by umeshgmrl** [conwnet/github1s#61]
Version 79.0.309.65 (Official build) (64-bit)

![image](https://user-images.githubusercontent.com/23176540/107602596-13c82780-6c50-11eb-99f7-7f511590bda2.png)

**Comment by ianpan870102** [comment]
Maybe update your Edge browser? I'm using "Version 88.0.705.63 (Official build) (64-bit)" and github1s works just fine.

**Comment by Siddhant-K-code** [comment]
Yes, It's working fine on all browsers of the new version.

**Comment by Siddhant-K-code** [comment]
It's Working Perfectly Fine on `Microsoft Edge - Version 88.0.705.63 (Official Build) (64-bit)`

![image](https://user-images.githubusercontent.com/55068936/107603225-0e6bdc80-6c52-11eb-9f5b-7a733ab7f6e3.png)

**Comment by xcv58** [comment]
Couldn't reproduce in `Microsoft Edge Version 88.0.705.63 (Official build) (64-bit)`
