### ISSUE TITLE
主题应用不上

### ISSUE THREAD

**Issue by violet2422** [conwnet/github1s#610]
当我安装了 night owl 主题后，
![image](https://github.com/user-attachments/assets/9d84d02a-21af-4c8c-b100-2fd528498fef)
点击 set color theme 后报错
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by violet2422** [comment]
![image](https://github.com/user-attachments/assets/899c79ae-c8a7-486b-84ac-87ca59e1a301)
![image](https://github.com/user-attachments/assets/84485580-5b08-4ac7-92df-7912425b2c8f)

**Comment by conwnet** [comment]
Thank you for the report, it has been fixed.
