### ISSUE TITLE
Disable the "Open with Github1s" Button for private repositories

### ISSUE THREAD

**Issue by TitusRobyK** [conwnet/github1s#63]
First of all , this github1s is absolutely amazing , let me take this moment to congratulate the team behind this
Thank You !!!

Now coming to the issue , For the github1s chrome extension , it would be great to Not show or disable the "Open with Github1s" Button for private repositories.

**Comment by conwnet** [comment]
It seems you are using the extension mentioned in issue #47 , it is developing by @fhefh2015 , you can ask for a help to him~

by the way, why you want disable "Open with Github1s" Button for private repositories? private repositories also works when you have set the GitHub OAuth Token...

**Comment by fhefh2015** [comment]
Great suggestion, I've updated the plugin.
Still have to wait, chrome is still under review.

![image](https://user-images.githubusercontent.com/14891797/107613432-450e1b00-6c83-11eb-8498-3e89c3630d2c.png)

**Comment by fhefh2015** [comment]
@TitusRobyK Ti
chrome audit approved, you can customize the options now

**Comment by TitusRobyK** [comment]
Wow ,So quick , Closing the issue
