### ISSUE TITLE
Support Golang syntax highlighting

### ISSUE THREAD

**Issue by Siddhant-K-code** [conwnet/github1s#66]

**Comment by Siddhant-K-code** [comment]
Which Icon to use: 

Option -1: 
![image](https://user-images.githubusercontent.com/55068936/107732158-ab477c00-6d1d-11eb-86ea-ef5f8abdeaff.png)


Option -2: 
![image](https://user-images.githubusercontent.com/55068936/107732167-b1d5f380-6d1d-11eb-98f9-a3903d7cabe5.png)

**Comment by conwnet** [comment]
@Siddhant-K-code it seems Golang syntax highlighting is provided by vscode natively, why provide a new one?

**Comment by Siddhant-K-code** [comment]
Yeah, I saw it later, that VSCode supports Golang highlighting. We can do both options, I can create a PR to remove the extensions/go-web as this feature is already there. or can leave as it is.

**Comment by conwnet** [comment]
In my opinion, I think use the original one would be better if there are no new fetures provide~🤣

**Comment by Siddhant-K-code** [comment]
ok, i will create a PR to remove `extensions/go-web`
