### ISSUE TITLE
Easy self hosting as personal vercel project

### ISSUE THREAD

**Issue by adityatelange** [conwnet/github1s#71]
It would be good idea to add a one click deploy button in Readme

- [Deploy Button Docs - Vercel](https://vercel.com/docs/more/deploy-button)
- It can be like this
   ```md
  [![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/git/external?repository-url=https%3A%2F%2Fgithub.com%2Fconwnet%2Fgithub1s&project-name=github1s&repo-name=github1s)
  ```
  [![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/git/external?repository-url=https%3A%2F%2Fgithub.com%2Fconwnet%2Fgithub1s&project-name=github1s&repo-name=github1s)

- Vercel by-default has build command `npm run build`, which when tested by me builds the project fine.
  Took aroud 14m to build.
- The only thing I noticed which hinders simplicity, is to set `Output Directory` to `dist`
  
  <details>

  ![image](https://user-images.githubusercontent.com/21258296/107623227-070ef800-6c7f-11eb-8a6b-f9a290dceb8f.png)
  </details>
- If the output of build command goes to `public` this could be super easy to setup our own vercel instance :)

**Comment by xcv58** [comment]
Related to https://github.com/conwnet/github1s/issues/33#issuecomment-776899096
