### ISSUE TITLE
Support for reading pull request and private repository

### ISSUE THREAD

**Issue by Wyfy0107** [conwnet/github1s#74]
Currently, github1s shows a vscode with no files in private repository. It would be nice also to to view pull request with this extension

**Comment by TitusRobyK** [comment]
By setting your oauth token , you would be able to see your private repository as well

**Comment by marzooq703** [comment]
How to set OAuth Token?

**Comment by rcoundon** [comment]
Are there any instructions on how to do this?

**Comment by marzooq703** [comment]
And for people who Don't know how to do this...
on the Side Pane, there's a Robot like Icon, from where You can set the OAuth
