### ISSUE TITLE
Free open source chrome/firefox extension

### ISSUE THREAD

**Issue by Darkempire78** [conwnet/github1s#75]
![](https://raw.githubusercontent.com/Darkempire78/Github1s-Extension/main/Capture1.PNG)
![](https://raw.githubusercontent.com/Darkempire78/Github1s-Extension/main/Capture2.PNG)

I created an open source extension which works for Chrome and Firefox

Link : https://github.com/Darkempire78/Github1s-Extension

**Comment by Darkempire78** [comment]
i added options 

![Capture3](https://user-images.githubusercontent.com/50015928/107654189-b6010300-6c82-11eb-8eb2-807c88d02c99.PNG)

**Comment by xcv58** [comment]
Thank you @Darkempire78 

Already put your link in README: https://github.com/conwnet/github1s#third-party-related-projects
