### ISSUE TITLE
Why is "read your browser history" permission is required?

### ISSUE THREAD

**Issue by anotheruser584** [conwnet/github1s#76]
Basically the title (started happening today).
Regarding everything else - great tool!

**Comment by fhefh2015** [comment]
https://github.com/fhefh2015/GitHub1s_chrome_extension/issues/1

I'm so sorry for that, i have changed the permission to activeTab.

**Comment by xcv58** [comment]
Fixed in https://github.com/fhefh2015/GitHub1s_chrome_extension/issues/1
Thank you @fhefh2015
