### ISSUE TITLE
Support For Jupyter Notebook File Format

### ISSUE THREAD

**Issue by MouadBH** [conwnet/github1s#77]

**Comment by image72** [comment]
Jupyter Notebook backkground need **python** or **nodejs** binary support, **github1s** just github-pages static only

**Comment by MouadBH** [comment]
what about using **https://github.com/jupyter/nbviewer** ?

**Comment by Siddhant-K-code** [comment]
Can we implement this for github1s: https://github.com/jithurjacob/vscode-nbpreviewer

**Comment by MouadBH** [comment]
hi @Siddhant-K-code, can I work on it?

**Comment by softmarshmallow** [comment]
@MouadBH  working on it [https://github.com/bridgedxyz/github.surf/tree/main/extensions/jupyter-web](). it's hard to integrate since it uses non browser apis

**Comment by Siddhant-K-code** [comment]
Yes, @MouadBH you can start and try to implement it.

**Comment by softmarshmallow** [comment]
https://github.com/bridgedxyz/github.surf/pull/15

Nailed it.

example: https://github.surf/deepmind/deepmind-research

**Comment by Siddhant-K-code** [comment]
ok, I will create a fork of it for this project.

**Comment by softmarshmallow** [comment]
@Siddhant-K-code Great!
