### ISSUE TITLE
中文会乱码

### ISSUE THREAD

**Issue by stydxm** [conwnet/github1s#9]
![Q KH31K@28K96}Q3F0GI8HU](https://user-images.githubusercontent.com/62790279/107166536-432d2900-69f1-11eb-9aba-b606162b6889.png)
如题，环境为Windows 10，firefox 85

**Comment by likongyang** [comment]
同样遇到，应该跟环境无关，而是对中文支持的问题

**Comment by conwnet** [comment]
中文乱码问题已经修复~
