### ISSUE TITLE
The text field is null while the blob is binary when use GitHub GraphQL API 

### ISSUE THREAD

**Issue by conwnet** [conwnet/github1s#90]
https://docs.github.com/en/graphql/reference/objects#blob

![image](https://user-images.githubusercontent.com/17734694/107751055-d6e75800-6d57-11eb-8aec-8cd552d688ac.png)

How should we handle the binary blob?😂

**Comment by xcv58** [comment]
Interesting https://github.com/octokit/graphql-schema/blob/master/schema.d.ts#L716

It seems there is no way to get binary content from GraphQL query. We could use the `isBinary` to determine whether it needs further action and use RESTful endpoint to retrieve the binary content.
