### ISSUE TITLE
[feature-request] Add Support for Vim navigation keybindings 

### ISSUE THREAD

**Issue by ddaza** [conwnet/github1s#95]
And maybe Emacs as well... (hai! 👋  Emacs friends)

I would love if there was an option to opt-in navigation keybinds. 
Most editors allow for this and there is a VSCode [extension](https://github.com/VSCodeVim/Vim) that can maybe be reused.

**Comment by timbaileyjones** [comment]
Absolutely!  No development environment is complete without vim!

**Comment by rfyiamcool** [comment]
@timbaileyjones  😁

**Comment by xcv58** [comment]
If we could do #162, users could install vim by themself.

**Comment by conwnet** [comment]
supported in #183 , you can install the `VIM` extension by yourself now~
