### ISSUE TITLE
Add prettier & make it auto format the code during commit

### ISSUE THREAD

**Issue by xcv58** [conwnet/github1s#97]
What's your opinion on prettier? It could easily coexist with eslint

https://www.robertcooper.me/using-eslint-and-prettier-in-a-typescript-project

**Comment by Siddhant-K-code** [comment]
It is Completed via #153 

Closing This Issue!

**Comment by conwnet** [comment]
Should we disable the prettier for `src/vs` directory, otherwise it will increase the complexity to merge a new version vscode.
@xcv58 @Siddhant-K-code

**Comment by xcv58** [comment]
> Should we disable the prettier for `src/vs` directory, otherwise it will increase the complexity to merge a new version vscode.
> @xcv58 @Siddhant-K-code

Sounds good, you can simply add the directory in the `.prettierignore` file.
