### ISSUE TITLE
Add GitHub action to deploy the gh-pages branch

### ISSUE THREAD

**Issue by xcv58** [conwnet/github1s#98]
It's a straightforward setup to deploy the assets via GitHub Action https://github.com/marketplace/actions/github-pages-action

And there are multiple deploy policies to use:
1. Deploy every master push
2. Deploy only new tag
3. Set a prod or deploy branch
4. Scheduled deploy

**Comment by conwnet** [comment]
Thanks, sounds wonderful, it is really dangerous to deploy it manual everytime.
For me, I prefer deploy it when only new tag push, because I am afraid the code in master is not very stable

**Comment by xcv58** [comment]
PR #122

**Comment by xcv58** [comment]
@conwnet  could you please try the GitHub action by push a tag when you have time? We could manually revert the gh-pages branch if there is any issue.

**Comment by conwnet** [comment]
ok, I will try it today～

**Comment by conwnet** [comment]
thanks! it works! @xcv58
